-- MySQL Script generated by MySQL Workbench
-- Tue Aug  4 23:47:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Shahafs
-- -----------------------------------------------------

USE `id14291323_shahafster` ;

-- -----------------------------------------------------
-- Table `id14291323_shahafster`.`BlogComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id14291323_shahafster`.`BlogComments` (
  `ID` INT NOT NULL,
  `Stamp` DATETIME NOT NULL,
  `Text` TEXT NOT NULL,
  `FeelingRate` INT NOT NULL,
  `active` INT NOT NULL DEFAULT '1',
  `file` LONGBLOB NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id14291323_shahafster`.`BlogDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id14291323_shahafster`.`BlogDetails` (
  `ID` INT NOT NULL,
  `password` VARCHAR(90) NOT NULL,
  `Stamp` DATETIME NOT NULL,
  `active` VARCHAR(45) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id14291323_shahafster`.`Visitors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id14291323_shahafster`.`Visitors` (
  `ID` INT NOT NULL,
  `FirstName` VARCHAR(125) NOT NULL,
  `LastName` VARCHAR(125) NOT NULL,
  `Stamp` DATETIME NOT NULL,
  PRIMARY KEY (`ID`, `LastName`, `FirstName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id14291323_shahafster`.`Likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id14291323_shahafster`.`Likes` (
  `Comment_ID` INT NOT NULL,
  `Visitors_ID` INT NOT NULL,
  `Visitors_LastName` VARCHAR(125) NOT NULL,
  `Visitors_FirstName` VARCHAR(125) NOT NULL,
  `Stamp` DATETIME NOT NULL,
  PRIMARY KEY (`Comment_ID`, `Visitors_ID`, `Visitors_LastName`, `Visitors_FirstName`),
  INDEX `fk_BlogComments_has_Visitors_Visitors2_idx` (`Visitors_ID` ASC, `Visitors_LastName` ASC, `Visitors_FirstName` ASC) ,
  INDEX `fk_BlogComments_has_Visitors_BlogComments2_idx` (`Comment_ID` ASC) ,
  CONSTRAINT `fk_BlogComments_has_Visitors_BlogComments2`
    FOREIGN KEY (`Comment_ID`)
    REFERENCES `id14291323_shahafster`.`BlogComments` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BlogComments_has_Visitors_Visitors2`
    FOREIGN KEY (`Visitors_ID` , `Visitors_LastName` , `Visitors_FirstName`)
    REFERENCES `id14291323_shahafster`.`Visitors` (`ID` , `LastName` , `FirstName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
